FROM ubuntu:trusty

# Try replacing the standard ubuntu archive with a faster mirror
RUN sed -i.bak 's/archive.ubuntu.com/mirrors.rit.edu/' /etc/apt/sources.list

# install Haskell, R dependencies, etc.
RUN apt-get update && apt-get install --assume-yes --no-install-recommends \
    apache2 \
    cabal-install \
    ca-certificates \
    ccache \
    gdebi \
    ghc \
    git \
    libcurl4-openssl-dev \
    libmysqlclient-dev \
    libpq-dev \
    libssl-dev \
    libx11-dev \
    libxml2-dev \
    lmodern \
    mysql-client \
    wget

# Install LaTeX
#   This package list was generated by running
#   `apt-cache depends texlive-full` and then excluding *-doc packages
RUN apt-get install --assume-yes --no-install-recommends \
    texlive-lang-polish  \
    texlive-generic-extra  \
    psutils  \
    latex-beamer  \
    info  \
    texlive-lang-indic  \
    texlive-lang-spanish  \
    latex-sanskrit  \
    texlive-omega  \
    texlive-lang-cyrillic  \
    texlive-lang-english  \
    prosper  \
    fragmaster  \
    texlive-base  \
    texlive-lang-european  \
    latexdiff  \
    latex-xcolor  \
    texlive-lang-african  \
    texlive-math-extra  \
    texlive-metapost  \
    texlive-lang-portuguese  \
    texlive-science  \
    tex4ht  \
    texlive-fonts-extra  \
    texlive-lang-italian  \
    dvidvi  \
    texlive-extra-utils  \
    texlive-luatex  \
    texlive-bibtex-extra  \
    latex-cjk-all  \
    texlive-latex-base  \
    texlive-font-utils  \
    texlive-fonts-recommended  \
    xindy  \
    texlive-pstricks  \
    lmodern  \
    texlive-lang-french  \
    texlive-xetex  \
    purifyeps  \
    latexmk  \
    texlive-lang-german  \
    lacheck  \
    texlive-lang-arabic  \
    texlive-plain-extra  \
    cm-super  \
    feynmf  \
    chktex  \
    tipa  \
    texlive-latex-recommended  \
    texlive-binaries  \
    texlive-music  \
    texlive-generic-recommended  \
    texlive-formats-extra  \
    texlive-humanities  \
    texlive-latex-extra  \
    texlive-publishers  \
    texlive-games  \
    pgf  \
    tex-gyre  \
    texlive-lang-greek  \
    texinfo  \
    context  \
    dvipng  \
    lcdf-typetools  \
    texlive-pictures  \
    texlive-lang-czechslovak  \
    texlive-lang-cjk  \
    t1utils  \
    texlive-lang-other

RUN cabal update && cabal install pandoc
RUN cabal update && cabal install pandoc-citeproc
